version: '3'

services:
  db:
    image: 'bitnami/postgresql'
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=rentxdb
    volumes:
      - 'pgdata:/bitnami/postgresql'
    networks:
      - app-net

  app:
    build: .
    container_name: api-rentx
    depends_on:
      - db
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  pgdata:
    driver: local
